### ISSUE TITLE
Try catch specific error

### ISSUE THREAD

**Issue by CaptainJojo** [neoziro/express-err#5]
Hi,

It's possible to try catch specify error with special methods, to not shudown server with error 500.

Exemple: I have error PG (postgresql), 
```
statusCode=500, message=missing FROM-clause entry for table "tete", stack=error: missing FROM-clause entry for table "tete"
```

I want catch just this error, and not all with

```
app.use(errorHandler({ formatters: ['json', 'text'], exitOnUncaughtException: false }));
```

**Comment by neoziro** [comment]
@CaptainJojo to do that, you must use a typed error like `PgError` and then add a middleware before `errorHandler` to catch it.

```js
app.use(function (req, res, next, err) {
  if (err instanceof PgError) {
    // do wathever you want
    return next();
  }
  next(err);
});
```

**Comment by CaptainJojo** [comment]
Thx, to your response
